import CreatorCenterPosts from "@/components/CreatorCenterPosts";
import { Metadata } from "next";
import React from "react";
import { IoTriangleSharp } from "react-icons/io5";

export const metadata: Metadata = {
    title: "Creator Center",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <>
            <div className="dots-background h-screen relative flex">
                <div className="place-self-center w-full flex flex-col items-center gap-16 lg:gap-6">
                    <div className="relative md:w-2/3 md:h-[300px] max-[768px]:p-4 border-[0.5px] border-gray-500 flex items-center justify-center gap-4 bg-gradient-to-r from-emerald-500/20 via-sky-500/20 to-orange-400/20 backdrop-blur-sm">
                        <IoTriangleSharp className="text-white text-[6rem] md:text-[12rem]" />
                        <h1 className="text-white text-4xl md:text-6xl">
                            Creator Center
                        </h1>
                        <div className="absolute max-[768px]:hidden top-[-20px] left-[-40px] backdrop-blur-sm bg-white/30 h-[100px] w-[100px]"></div>
                        <div className="absolute max-[768px]:hidden bottom-[-120px] left-[-60px] backdrop-blur-sm bg-white/30 h-[140px] w-[140px]"></div>
                        <div className="absolute max-[768px]:hidden top-[-50px] left-[-60px] backdrop-blur-sm bg-white/30 h-[50px] w-[50px]"></div>{" "}
                        <div className="absolute max-[768px]:hidden bottom-[-40px] right-[-70px] backdrop-blur-sm bg-white/30 h-[120px] w-[120px]"></div>
                        <div className="absolute max-[768px]:hidden top-[-120px] right-[-70px] backdrop-blur-sm bg-white/30 h-[100px] w-[100px]"></div>
                        <div className="absolute max-[768px]:hidden top-[-40px] right-[80px] backdrop-blur-sm bg-white/30 h-[40px] w-[40px]"></div>
                        <div className="absolute max-[768px]:hidden bottom-[-70px] right-[-80px] backdrop-blur-sm bg-white/30 h-[60px] w-[60px]"></div>
                    </div>
                </div>
            </div>
            <div className="bg-white">
                <CreatorCenterPosts />
            </div>
        </>
    );
};

export default page;
