import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Provider";
import ScrollToTop from "@/components/ScrollToTop";
import ReduxPersist from "@/components/ReduxPersist";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Economist",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <ReduxPersist>
                        <Navbar />
                        {children}
                        <Footer />
                        <ScrollToTop />
                    </ReduxPersist>
                </Providers>
            </body>
        </html>
    );
}
